import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import TableContainer from "../components/Table";
import { DatePicker } from "antd";

import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main>
        {/* <Link href="/">
          <a>Home</a>
        </Link> */}
           <TableContainer />
      </main>
   
    </div>
  );
}
